;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-babel-insert-hyphen
	LaTeX-insert-left-brace
	TeX-insert-backslash
	TeX-insert-dollar
	TeX-newline
	beginning-of-visual-line
	c-electric-brace
	c-electric-colon
	c-electric-paren
	c-electric-semi&comma
	c-electric-star
	dove-backward-kill-word
	dove-forward-kill-word
	end-of-visual-line
	enlarge-window-horizontally
	forward-sexp
	kill-region
	org-force-self-insert
	org-return
	orgtbl-hijacker-command-100
	orgtbl-hijacker-command-102
	orgtbl-hijacker-command-109
	orgtbl-self-insert-command
	overwrite-mode
	reindent-then-newline-and-indent
	sh-assignment
	smex
	vhdl-beautify-buffer
	vhdl-electric-close-bracket
	vhdl-electric-comma
	vhdl-electric-dash
	vhdl-electric-open-bracket
	vhdl-electric-quote
	vhdl-electric-return
	vhdl-electric-semicolon
	vhdl-electric-space
	vhdl-electric-tab
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	c-electric-lt-gt
	indent-for-tab-command
	mouse-set-region
	org-self-insert-command
	view-emacs-todo
	))
